import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/providers/sessionProvider";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ToastProvider from "@/providers/toastProvider";
import React from "react";

const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ['latin'],
    variable: '--font-poppins'
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <NextAuthSessionProvider>
            <html lang="pt-br">
            <body
                className={`${poppins.className} ${poppins.variable} flex flex-col font-poppins justify-center items-center h-screen bg-gray-900`}>
            <ToastProvider>
                {children}
            </ToastProvider>
            </body>
            </html>
        </NextAuthSessionProvider>
    );
}
