version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: rings-of-power
      MYSQL_USER: yasmin-walsh
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
#   version: "3.8"

# services:
#   mysql:
#     image: mysql:latest
#     container_name: mysql_container
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${DB_DATABASE}
#       MYSQL_USER: ${DB_USER}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#     ports:
#       - "${DB_PORT}:${DB_PORT}"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
