version: '3.7'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data: