CREATE TABLE rings (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  power VARCHAR(100) NOT NULL,
  carrier VARCHAR(100) NOT NULL,
  forger VARCHAR(100) NOT NULL,
  image VARCHAR(255) NOT NULL
);